=== kaushik-04/wtwarm-terraform-teample/Utilities/Utilities/PolicyAsCodeFramework/Definitions/initiativeDefinitionSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "The Root Schema",
    "description": "The root schema comprises the entire JSON document.",    
    "required": [
        "name",
        "displayName",
        "description",
        "metadata",
        "policyDefinitions",
        "parameters"
    ],
    "properties": {
        "name": {
            "$id": "#/properties/name",
            "type": "string",
            "minLength": 1,
            "maxLength": 128,
            "title": "The Initiative-name Schema",
            "description": "Name of the Initiative",
            "default": "",
            "examples": [
                "BillingTagInitiative"
            ]
        },
        "displayName": {
            "$id": "#/properties/displayName",
            "type": "string",
            "minLength": 1,
            "maxLength": 128,
            "title": "The Initiative-displayname Schema",
            "description": "Displayname of the Initiative",
            "default": "",
            "examples": [
                "Billing Tags Policy Initiative"
            ]
        },
        "description": {
            "$id": "#/properties/description",
            "type": "string",
            "minLength": 1,
            "maxLength": 512,
            "title": "The Initiative description Schema",
            "description": "Description of the Initiative.",
            "default": "",
            "examples": [
                "Specify tags used for billing (e.g. CostCenter and OwnerEmail)"
            ]
        },
        "metadata": {
            "$id": "#/properties/metadata",
            "type": "object",
            "title": "The Metadata Schema",
            "description": "Metadata for the Initiative.",
            "default": {},
            "additionalProperties": true,
            "required": [
                "category"
            ],
            "properties": {
                "category": {
                    "$id": "#/properties/metadata/properties/category",
                    "type": "string",
                    "title": "The Category Schema",
                    "description": "The category of the Initiative",
                    "default": ""
                }
            }
        },
        "policyDefinitions": {
            "$id": "#/properties/policyDefinitions",
            "type": "array",
            "minItems": 1,
            "maxItems": 100,
            "uniqueItems": true,
            "title": "The policyDefinitions Schema",
            "description": "Here all the referenced policyDefinitions, that are grouped within this initiative are defined.",
            "additionalItems": true,
            "items": {
                "$id": "#/properties/policyDefinitions/items",
                "type": "object",
                "title": "The Items Schema",
                "description": "Id and parameters for the referenced policyDefinitions",
                "additionalProperties": false,
                "required": [
                    "policyDefinitionId",
                    "parameters"
                ],
                "properties": {
                    "policyDefinitionId": {
                        "$id": "#/properties/policyDefinitions/items/properties/policyDefinitionId",
                        "type": "string",
                        "title": "The policyDefinitionID Schema",
                        "description": "A policyDefinitionID that shall be part of the Initiative",
                        "default": "",
                        "oneOf": [
                            { "pattern": "^/providers/Microsoft.Authorization/policyDefinitions/([a-f]|[0-9]){8}-([a-f]|[0-9]){4}-([a-f]|[0-9]){4}-([a-f]|[0-9]){4}-([a-f]|[0-9]){12}$" },
                            { "pattern": "^/subscriptions/([a-f]|[0-9]){8}-([a-f]|[0-9]){4}-([a-f]|[0-9]){4}-([a-f]|[0-9]){4}-([a-f]|[0-9]){12}/providers/Microsoft.Authorization/policyDefinitions/.+[^/]$" },
                            { "pattern": "^/providers/Microsoft.Management/managementGroups/[^/]+/providers/Microsoft.Authorization/policyDefinitions/.+[^/]$" }
                        ],
                        "examples": [
                            "/providers/Microsoft.Authorization/policyDefinitions/cd3aa116-8754-49c9-a813-ad46512ece54"
                        ]

                    },
                    "parameters": {
                        "$id": "#/properties/policyDefinitions/items/properties/parameters",
                        "type": "object",
                        "minProperties": 0,
                        "maxProperties": 20,
                        "title": "The Parameters Schema",
                        "description": "All parameters required by the policy definitionID",
                        "default": {}
                    },
                    "policyDefinitionReferenceId": {
                        "$id": "#/properties/policyDefinitions/items/properties/policyDefinitionReferenceId",
                        "type": "string",
                        "title": "The policyDefinitionReferenceId Schema",
                        "description": "A policyDefinitionReferenceId is an optional part of the Initiative",
                        "default": ""                        
                    },
                    "groupNames": {
                        "$id": "#/properties/policyDefinitions/items/properties/groupNames",
                        "type": "array",
                        "title": "The groupName Schema",
                        "description": "A groupName is an optional part of the Initiative",
                        "default": []
                    }
                }
            }
        },
        "parameters": {
            "$id": "#/properties/properties/properties/parameters",
            "type": "object",
            "minProperties": 0,
            "maxProperties": 100,
            "title": "The Parameters Schema",
            "description": "Parameters for the Initiative definition that can be used within the various policyDefinition parameters",
            "default": {}
        },
        "policyDefinitionGroups": {
            "$id": "#/properties/policyDefinitionGroups",
            "type": "array",
            "title": "The policyDefinitionGroups Schema",
            "description": "Definition of policyDefinitionGroups that can be used to group the various policyDefinitions",
            "default": {}
        }
    }
}

=== kaushik-04/wtwarm-terraform-teample/Utilities/Utilities/PolicyAsCodeFramework/Definitions/InitiativeDefinitions/Test/initiative-test.json
{  
    "name": "testInitiativeDefinition",
    "displayName": "testInitiativeDefinition",
    "description": "This is test initiative as at least one needs to be in place",
    "metadata": {
        "category": "General"
    },
    "parameters": {
        "allowedLocationParam": {
            "type": "array",
            "metadata": {
                "displayName": "Allowed Location"
            },            
            "allowedValues": [
                "westeurope",
                "northeurope"
            ]
        },
        "testParam1": {
            "type": "boolean",
            "metadata": {
                "displayName": "test"
            }
        }
    },
    "policyDefinitions": [
          {
            "policyDefinitionId": "/providers/Microsoft.Management/managementGroups/123456789-1234-1234-1234-123456789012/providers/Microsoft.Authorization/policyDefinitions/AuditKeyVaultLocation",
            "parameters": {
                "allowedLocation": {
                    "value": "[parameters('allowedLocationParam')]"
                }
            }
          },
          {
            "policyDefinitionId": "/providers/Microsoft.Management/managementGroups/123456789-1234-1234-1234-123456789012/providers/Microsoft.Authorization/policyDefinitions/ParamTest",
            "parameters": {
                "myBoolean": {
                    "value": "[parameters('testParam1')]"
                }
            }
          }
    ]
}

=== kaushik-04/wtwarm-terraform-teample/Utilities/Utilities/Hydration/src/Tests/e2e/lib/ccoe/RepoContent/Azure-ESP/iac-modules/modules/virtualmachine/1.0/policies/initiativeDefinitions/pxs-cn-s-vm-pi.json
{
    "name": "pxs-cn-s-vm-pi",
    "displayName": "pxs-cn-s-vm-pi",
    "description": "Initiative definition for Virtual Machines",
    "metadata": {
        "category": "CCoE"
    },
    "policyDefinitions": [
        {
            "policyDefinitionId": "/providers/Microsoft.Management/managementGroups/pxs-cloudnative-mg/providers/Microsoft.Authorization/policyDefinitions/pxs-cn-vm-antimalware-pd",
            "parameters": {
                "effect": {
                    "value": "[parameters('antimalwareeffect')]"
                }
            }
        },
        {
            "policyDefinitionId": "/providers/Microsoft.Management/managementGroups/pxs-cloudnative-mg/providers/Microsoft.Authorization/policyDefinitions/pxs-cn-vm-bootdiagnostics-pd",
            "parameters": {
                "effect": {
                    "value": "[parameters('bootdiagnosticseffect')]"
                }
            }
        },
        {
            "policyDefinitionId": "/providers/Microsoft.Management/managementGroups/pxs-cloudnative-mg/providers/Microsoft.Authorization/policyDefinitions/pxs-cn-vm-dependency-pd",
            "parameters": {
                "effect": {
                    "value": "[parameters('depencyagenteffect')]"
                }
            }
        },
        {
            "policyDefinitionId": "/providers/Microsoft.Management/managementGroups/pxs-cloudnative-mg/providers/Microsoft.Authorization/policyDefinitions/pxs-cn-vm-extensions-pd",
            "parameters": {
                "effect": {
                    "value": "[parameters('vmextensionseffect')]"
                },
                "approvedExtensions": {
                    "value": "[parameters('approvedExtensions')]"
                }
            }
        },
        {
            "policyDefinitionId": "/providers/Microsoft.Management/managementGroups/pxs-cloudnative-mg/providers/Microsoft.Authorization/policyDefinitions/pxs-cn-vm-os-restriction-pd",
            "parameters": {
                "effect": {
                    "value": "[parameters('osrestrictioneffect')]"
                },
                "allowedWindowsSKUImages": {
                    "value": "[parameters('allowedWindowsSKUImages')]"
                }
            }
        },
        {
            "policyDefinitionId": "/providers/Microsoft.Management/managementGroups/pxs-cloudnative-mg/providers/Microsoft.Authorization/policyDefinitions/pxs-cn-vm-os-update-pd",
            "parameters": {
                "effect": {
                    "value": "[parameters('guestosupdateeffect')]"
                }
            }
        }
    ],
    "parameters": {
        "approvedExtensions": {
            "type": "Array",
            "metadata": {
                "displayName": "allowed VM extensions",
                "description": "Only approved VM extensions should be installed."
            },
            "defaultValue": [
                "AzureDiskEncryption",
                "AzureDiskEncryptionForLinux",
                "DependencyAgentWindows",
                "DependencyAgentLinux",
                "IaaSAntimalware",
                "IaaSDiagnostics",
                "LinuxDiagnostic",
                "MicrosoftMonitoringAgent",
                "NetworkWatcherAgentLinux",
                "NetworkWatcherAgentWindows",
                "OmsAgentForLinux",
                "VMSnapshot",
                "VMSnapshotLinux",
                "DSC",
                "LinuxAgent.AzureSecurityCenter",
                "WindowsAgent.AzureSecurityCenter",
                "guesthealthwindowsagent",
                "azuremonitorwindowsagent",
                "SqlIaaSAgent",
                "azurebackupwindowsworkload",
                "CustomScript"
            ]
        },
        "vmextensionseffect": {
            "type": "string",
            "metadata": {
                "displayName": "allowed Virutal Machine  extensions effect",
                "description": "allowed Virutal Machine  extensions Effect."
            },
            "defaultValue": "Audit",
            "allowedValues": [
                "Audit",
                "Deny",
                "Disabled"
            ]
        },
        "antimalwareeffect": {
            "type": "String",
            "metadata": {
                "displayName": "Antimaleware effect ",
                "description": "Enable or disable the execution of the policy"
            },
            "allowedValues": [
                "AuditIfNotExists",
                "Disabled"
            ],
            "defaultValue": "AuditIfNotExists"
        },
        "bootdiagnosticseffect": {
            "type": "String",
            "metadata": {
                "displayName": "Boot Diagnostics effect ",
                "description": "Enable or disable the execution of the policy"
            },
            "allowedValues": [
                "Audit",
                "Deny",
                "Disabled"
            ],
            "defaultValue": "Audit"
        },
        "depencyagenteffect": {
            "type": "String",
            "metadata": {
                "displayName": "Dependency Agent effect",
                "description": "Enable or disable the execution of the policy"
            },
            "allowedValues": [
                "AuditIfNotExists",
                "Disabled"
            ],
            "defaultValue": "AuditIfNotExists"
        },
        "osrestrictioneffect": {
            "type": "String",
            "metadata": {
                "displayName": "Operating System restriction effect",
                "description": "The effect determines what happens when the policy rule is evaluated to match"
            },
            "allowedValues": [
                "Audit",
                "Deny",
                "Disabled"
            ],
            "defaultValue": "Audit"
        },
        "allowedwindowsskuimages": {
            "type": "array",
            "metadata": {
                "displayName": "allowed SKU image effect",
                "description": "allowed SKU Image for VMs"
            },
            "allowedValues": [],
            "DefaultValue": [
                "2012-R2-Datacenter",
                "2016-Datacenter-Server-Core",
                "2016-Datacenter",
                "2019-Datacenter-Core",
                "2019-Datacenter"
            ]
        },
        "guestosupdateeffect": {
            "type": "String",
            "metadata": {
                "displayName": "Guest OS Update Effect",
                "description": "The effect determines what happens when the policy rule is evaluated to match"
            },
            "allowedValues": [
                "Audit",
                "Deny",
                "Disabled"
            ],
            "defaultValue": "Audit"
        }
    }
}
